name: roome_android
description: A study rooms application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  provider: ^6.1.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^9.0.0
  lottie: ^2.7.0
  confetti: ^0.7.0
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Eğer assets klasörünüz varsa:
  # assets:
  #   - assets/images/
  #   - assets/animations/

  # Eğer custom fontlar kullanıyorsanız:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf

# macOS için gerekli yapılandırmalar
macos:
  version: 1.0.0
  schema_version: 2
